#!/bin/bash
# dockweb - common helpers

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# Project root (where dockweb lives)
DOCKWEB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log_info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*"; }

header() {
    echo ""
    echo -e "${BOLD}${CYAN}$*${NC}"
    echo -e "${DIM}$(printf '%.0s─' $(seq 1 40))${NC}"
}

confirm() {
    local msg="${1:-Continue?}"
    local default="${2:-n}"
    local prompt
    if [[ "$default" == "y" ]]; then
        prompt="[Y/n]"
    else
        prompt="[y/N]"
    fi
    echo -ne "${YELLOW}$msg $prompt ${NC}"
    read -r answer
    answer="${answer:-$default}"
    [[ "$answer" =~ ^[Yy] ]]
}

load_env() {
    local env_file="${DOCKWEB_ROOT}/.env"
    if [[ -f "$env_file" ]]; then
        set -a
        source <(grep -v '^\s*#' "$env_file" | grep -v '^\s*$')
        set +a
    fi
}

validate_domain() {
    local domain="$1"
    if [[ "$domain" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*\.[a-zA-Z]{2,}$ ]]; then
        return 0
    fi
    return 1
}

sanitize_domain() {
    echo "$1" | sed 's/[.\-]/_/g'
}

get_site_conf() {
    local domain="$1"
    local conf="${DOCKWEB_ROOT}/sites/${domain}/.dockweb.conf"
    if [[ -f "$conf" ]]; then
        source "$conf"
        return 0
    fi
    return 1
}

list_all_sites() {
    local sites=()
    local conf
    for conf in "${DOCKWEB_ROOT}"/sites/*/.dockweb.conf; do
        [[ -f "$conf" ]] || continue
        local domain
        domain=$(grep '^DOMAIN=' "$conf" | cut -d= -f2)
        [[ -n "$domain" ]] && sites+=("$domain")
    done
    if [[ ${#sites[@]} -gt 0 ]]; then
        printf '%s\n' "${sites[@]}"
    fi
}

site_count() {
    list_all_sites | wc -l
}

docker_compose_cmd() {
    echo "docker compose -f ${DOCKWEB_ROOT}/docker-compose.yml -f ${DOCKWEB_ROOT}/docker-compose.sites.yml"
}

generate_password() {
    openssl rand -base64 24 | tr -d '/+=' | head -c 32
}

check_dependencies() {
    local missing=()
    command -v docker &>/dev/null || missing+=("docker")
    docker compose version &>/dev/null || missing+=("docker-compose-plugin")
    command -v openssl &>/dev/null || missing+=("openssl")
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing dependencies: ${missing[*]}"
        log_info "Run 'dockweb setup' to install them."
        return 1
    fi
    return 0
}

is_running() {
    local cmd
    cmd="$(docker_compose_cmd)"
    $cmd ps --status running 2>/dev/null | grep -q "Up\|running" 2>/dev/null
}

ensure_sites_compose() {
    local f="${DOCKWEB_ROOT}/docker-compose.sites.yml"
    if [[ ! -f "$f" ]]; then
        cat > "$f" <<'EOF'
# Auto-generated by dockweb - DO NOT EDIT MANUALLY
services: {}

networks:
  web_network:
    driver: bridge
EOF
    fi
}
