server {
    listen 80;
    server_name site-a.com; # Domain của site A

    # Lưu ý đường dẫn root phải khớp với volume mapping trong docker-compose
    root /var/www/sites/site-a/public;
    index index.php index.html;

    access_log /var/log/nginx/site-a-access.log;
    error_log /var/log/nginx/site-a-error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        # QUAN TRỌNG: Trỏ đúng vào tên service của Site A
        fastcgi_pass php_site_a:9000;

        fastcgi_index index.php;
        include fastcgi_params;
        # $document_root ở đây là /var/www/sites/site-a/public (Nginx nhìn thấy)
        # PHP Container Site A cũng cần có đường dẫn này (đã map volume khớp nhau)
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
