server {
    listen 80;
    server_name kairoxbuild.com www.kairoxbuild.com;

    root /var/www/sites/kairoxbuild.com/public;
    index index.php index.html;

    access_log /var/log/nginx/kairoxbuild.com-access.log;
    error_log /var/log/nginx/kairoxbuild.com-error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php_kairoxbuild:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}