# {{DOMAIN}} - Let's Encrypt SSL
# Auto-generated by dockweb - regenerate with: dockweb ssl {{DOMAIN}} letsencrypt

# HTTP to HTTPS redirect
server {
    listen 80;
    server_name {{DOMAIN}} www.{{DOMAIN}};

    # Allow Certbot validation
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    server_name {{DOMAIN}} www.{{DOMAIN}};

    root /var/www/sites/{{DOMAIN}}/public;
    index index.php index.html;

    # SSL Configuration (Let's Encrypt)
    ssl_certificate /etc/letsencrypt/live/{{DOMAIN}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{DOMAIN}}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Logging
    access_log /var/log/nginx/{{DOMAIN}}-access.log;
    error_log /var/log/nginx/{{DOMAIN}}-error.log;

    # Rate limiting
    limit_req zone=general burst=20 nodelay;
    limit_conn conn_limit 10;

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    # Static files with browser caching
    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|css|js|woff|woff2|ttf|eot|otf)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        tcp_nodelay off;
        open_file_cache max=1000 inactive=120s;
        open_file_cache_valid 45s;
        open_file_cache_min_uses 2;
        open_file_cache_errors off;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Main location block
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP processing with FastCGI cache
    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass {{PHP_CONTAINER}}:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # FastCGI Cache
        fastcgi_cache PHPCACHE;
        fastcgi_cache_bypass $http_pragma $http_authorization;
        fastcgi_no_cache $http_pragma $http_authorization;
        add_header X-FastCGI-Cache $upstream_cache_status;

        # Performance tuning
        fastcgi_buffer_size 128k;
        fastcgi_buffers 256 16k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;
    }

    # Stricter rate limiting for login/admin pages
    location ~* (login|admin|wp-admin|administrator) {
        limit_req zone=login burst=3 nodelay;

        try_files $uri $uri/ /index.php?$query_string;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass {{PHP_CONTAINER}}:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            # Disable cache for admin areas
            fastcgi_cache_bypass 1;
            fastcgi_no_cache 1;
        }
    }
}
