# {{DOMAIN}} - Local Dev with HTTPS (mkcert, served as {{LOCAL_DOMAIN}})
# Auto-generated by dockweb - regenerate with: dockweb ssl {{DOMAIN}} dev-ssl
# Add to /etc/hosts: 127.0.0.1  {{LOCAL_DOMAIN}} www.{{LOCAL_DOMAIN}}

# HTTP to HTTPS redirect
server {
    listen 80;
    server_name {{LOCAL_DOMAIN}} www.{{LOCAL_DOMAIN}};

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl;
    http2 on;
    server_name {{LOCAL_DOMAIN}} www.{{LOCAL_DOMAIN}};

    root /var/www/sites/{{DOMAIN}}/public;
    index index.php index.html;

    # SSL Configuration (mkcert local CA)
    ssl_certificate /etc/nginx/local-certs/{{DOMAIN}}/cert.pem;
    ssl_certificate_key /etc/nginx/local-certs/{{DOMAIN}}/key.pem;

    # Security Headers (no HSTS for local dev)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;

    # Logging
    access_log /var/log/nginx/{{DOMAIN}}-access.log;
    error_log /var/log/nginx/{{DOMAIN}}-error.log;

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    # Static files with browser caching
    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|css|js|woff|woff2|ttf|eot|otf)$ {
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Main location block
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP processing
    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass {{PHP_CONTAINER}}:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Performance tuning
        fastcgi_buffer_size 128k;
        fastcgi_buffers 256 16k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;
    }

    # Admin pages
    location ~* (login|admin|wp-admin|administrator) {
        try_files $uri $uri/ /index.php?$query_string;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass {{PHP_CONTAINER}}:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
